var effectsConfig = {
    "greenBang":{
        "png":"art/greenBang.png",
        "plist":"art/greenBang.plist",
        "start":"greenBang.1.png",
        "placement":"center",
        "frames":28,
        "delay":0.02,
        "times":1
    },
    "explosion":{
        "png":"art/explosion.png",
        "plist":"art/explosion.plist",
        "start":"explosion.1.png",
        "placement":"bottom",
        "zorder":"behind",
        "frames":27,
        "delay":0.01,
        "offset":{
            "x":0,
            "y":50
        },
        "times":1
    },
    "blueRadius":{
        "png":"art/blueRadius.png",
        "plist":"art/blueRadius.plist",
        "start":"blueRadius.1.png",
        "frames":23,
        "delay":0.1,
        "zorder":"behind",
        "placement":"bottom",
        "offset":{
            "x":-5,
            "y":5
        }

    },
    "heal":{
        "png":"art/heal.png",
        "plist":"art/heal.plist",
        "start":"heal.5.png",
        "frames":17,
        "delay":0.05,
        "placement":"bottom",
        "times":5,
    },
    "teleport":{
        "png":"art/teleport.png",
        "plist":"art/teleport.plist",
        "start":"teleport.1.png",
        "frames":14,
        "delay":0.02,
        "placement":"base2base",
        "times":1,
    },
    "fire":{
        "png":"art/fire.png",
        "plist":"art/fire.plist",
        "start":"fire.1.png",
        "frames":44,
        "delay":0.02,
        "placement":"base2base",
        "zorder":"behind",
    },
    "poison":{
        "png":"art/poison.png",
        "plist":"art/poison.plist",
        "start":"poison.1.png",
        "frames":50,
        "delay":0.02,
//        "offset":{
//            "x":0,
//            "y":100
//        },
        "placement":"bottom",
    }
}

