var effectsConfig = {
    "greenBang":{
        "png":"art/greenBang.png",
        "plist":"art/greenBang.plist",
        "start":"greenBang.1.png",
        "placement":"center",
        "frames":28,
        "delay":0.02,
        "times":1
    },
    "blueRadius":{
        "png":"art/blueRadius.png",
        "plist":"art/blueRadius.plist",
        "start":"blueRadius.1.png",
        "frames":47,
        "delay":0.02,
        "placement":"bottom",
        "offset":{
            "x":-5,
            "y":5
        }

    },
    "heal":{
        "png":"art/heal.png",
        "plist":"art/heal.plist",
        "start":"heal.5.png",
        "frames":17,
        "delay":0.02,
        "placement":"bottom",
        "times":1,
    },
    "teleport":{
        "png":"art/teleport.png",
        "plist":"art/teleport.plist",
        "start":"teleport.1.png",
        "frames":14,
        "delay":0.02,
        "placement":"base2base",
        "times":1,
    }
}

