var powerTiles = {
    "fireBall":{
        "png":"art/powerTiles.png",
        "plist":"art/powerTiles.plist",
        "icon":"Fire4.png"
    },
    "poisonCloud":{
        "png":"art/powerTiles.png",
        "plist":"art/powerTiles.plist",
        "icon":"Poison4.png"
    },
    "lightningBolt":{
        "png":"art/powerTiles.png",
        "plist":"art/powerTiles.plist",
        "icon":"Holy1.png"
    },
    "healing":{
        "png":"art/powerTiles.png",
        "plist":"art/powerTiles.plist",
        "icon":"Holy5.png"
    },
    "leech":{
        "png":"art/powerTiles.png",
        "plist":"art/powerTiles.plist",
        "icon":"Shadow4.png"
    },
    "iceStorm":{
        "png":"art/powerTiles.png",
        "plist":"art/powerTiles.plist",
        "icon":"Frost5.png"
    },

}