var effectsConfig = {
    "greenBang":{
        "png":"art/greenBang.png",
        "plist":"art/greenBang.plist",
        "start":"greenBang.1.png",
        "placement":"center",
        "frames":28,
        "delay":0.02,
        "times":1
    },
    "explo":{
        "png":"art/effects{v}.png",
        "plist":"art/effects{v}.plist",
        "start":"explo.1.png",
        "placement":"bottom",
        "zorder":"behind",
        "frames":23,
        "delay":0.03,
        "offset":{
            "x":0,
            "y":0
        },
        "times":1,
        "flash":true,
        "shake":true
    },
    "healingRadius":{
        "png":"art/effects{v}.png",
        "plist":"art/effects{v}.plist",
        "start":"healingRadius.1.png",
        "frames":39,
        "delay":0.05,
        "zorder":"behind",
        "placement":"center",
        "offset":{
            "x":0,
            "y":0
        }

    },
    "heal":{
        "png":"art/effects{v}.png",
        "plist":"art/effects{v}.plist",
        "start":"heal.1.png",
        "frames":50,
        "delay":0.05,
        "placement":"center",
        "scaleToTarget":2,
        "zorder":"behind"

    },
    "teleport":{
        "png":"art/teleport.png",
        "plist":"art/teleport.plist",
        "start":"teleport.1.png",
        "frames":14,
        "delay":0.02,
        "placement":"base2base",
        "times":1
    },
    "movement":{
        "png":"art/touch.png",
        "plist":"art/touch.plist",
        "start":"movement.1.png",
        "frames":8,
        "delay":0.05,
        "placement":"bottom",
        "times":2
    },
    "characterSelect":{
        "png":"art/touch.png",
        "plist":"art/touch.plist",
        "start":"characterSelect.1.png",
        "frames":7,
        "delay":0.05,
        "placement":"bottom",
        "zorder":"behind"
    },
    "enemySelection":{
        "png":"art/touch.png",
        "plist":"art/touch.plist",
        "start":"enemySelection.1.png",
        "frames":7,
        "delay":0.05,
        "placement":"base2base",
        "zorder":"behind",
        "times":2
    },
    "allySelection":{
        "png":"art/touch.png",
        "plist":"art/touch.plist",
        "start":"allySelection.1.png",
        "frames":7,
        "delay":0.05,
        "placement":"base2base",
        "zorder":"behind",
        "times":2
    },
    "burning":{
        "png":"art/effects{v}.png",
        "plist":"art/effects{v}.plist",
        "start":"burning.1.png",
        "frames":33,
        "delay":0.02,
        "placement":"bottom",
        "zorder":"behind",
        "offset":{
            "x":0,
            "y":65
        },
        "times":6
    },
    "poisoned2":{
        "png":"art/effects{v}.png",
        "plist":"art/effects{v}.plist",
        "start":"poisoned2.1.png",
        "frames":24,
        "delay":0.05,
        "placement":"center",
        "zorder":"behind",
        "scaleToTarget":2,
        "offset":{
            "x":0,
            "y":25
        }

    },
    "lifeDrain":{
        "png":"art/effects{v}.png",
        "plist":"art/effects{v}.plist",
        "start":"lifeDrain.1.png",
        "frames":38,
        "delay":0.05,
        "placement":"center",
        "zorder":"front",
        "scaleToTarget":2,
        "offset":{
            "x":0,
            "y":25
        }
    },
    "vampireRadius":{
        "png":"art/effects{v}.png",
        "plist":"art/effects{v}.plist",
        "start":"vampireRadius.1.png",
        "frames":30,
        "delay":0.05,
        "placement":"bottom",
        "zorder":"behind",
        "scaleToTarget":2,
        "offset":{
            "x":0,
            "y":25
        }
    },
    "voidFire":{
        "png":"art/effects{v}.png",
        "plist":"art/effects{v}.plist",
        "start":"voidFire.1.png",
        "frames":32,
        "delay":0.05,
        "placement":"center",
        "zorder":"behind",
        "scaleToTarget":2,
        "offset":{
            "x":0,
            "y":25
        }
    },
    "hit":{
        "png":"art/effects{v}.png",
        "plist":"art/effects{v}.plist",
        "start":"hit.1.png",
        "frames":20,
        "delay":0.05,
        "placement":"center",
        "zorder":"front",
        "times":1,
        "offset":{
            "x":0,
            "y":25
        }
    }

}

