var effectsConfig = {
    "greenBang":{
        "png":"art/greenBang{v}.png",
        "plist":"art/greenBang{v}.plist",
        "start":"greenBang.1.png",
        "placement":"center",
        "frames":28,
        "delay":0.02,
        "times":1
    },
    "explosion":{
        "png":"art/explosion{v}.png",
        "plist":"art/explosion{v}.plist",
        "start":"explosion.1.png",
        "placement":"bottom",
        "zorder":"behind",
        "frames":27,
        "delay":0.01,
        "offset":{
            "x":0,
            "y":50
        },
        "times":1
    },
    "blueRadius":{
        "png":"art/blueRadius{v}.png",
        "plist":"art/blueRadius{v}.plist",
        "start":"blueRadius.1.png",
        "frames":23,
        "delay":0.05,
        "zorder":"behind",
        "placement":"bottom",
        "offset":{
            "x":-5,
            "y":-110
        }

    },
    "heal":{
        "png":"art/heal{v}.png",
        "plist":"art/heal{v}.plist",
        "start":"heal.5.png",
        "frames":17,
        "delay":0.05,
        "placement":"bottom",
        "times":5,
    },
    "teleport":{
        "png":"art/teleport{v}.png",
        "plist":"art/teleport{v}.plist",
        "start":"teleport{v}.1.png",
        "frames":14,
        "delay":0.02,
        "placement":"base2base",
        "times":1,
    },
    "tapEffect":{
        "png":"art/tap{v}.png",
        "plist":"art/tap{v}.plist",
        "start":"tapEffect.1.png",
        "frames":15,
        "delay":0.02,
        "placement":"bottom",
        "times":1,
    },
    "selectEffect":{
        "png":"art/select{v}.png",
        "plist":"art/select{v}.plist",
        "start":"selectEffect.1.png",
        "frames":31,
        "delay":0.02,
        "placement":"base2base",
        "zorder":"behind",

    },
    "fire":{
        "png":"art/fire{v}.png",
        "plist":"art/fire{v}.plist",
        "start":"fire.1.png",
        "frames":44,
        "delay":0.02,
        "placement":"base2base",
        "zorder":"behind",
    },
    "fireLoop":{
        "name":"fire",
        "png":"art/fire{v}.png",
        "plist":"art/fire{v}.plist",
        "start":"fire.1.png",
        "frames":44,
        "delay":0.02,
        "placement":"base2base",
        "zorder":"behind",
        "times":15,
    },
    "poison":{
        "png":"art/poison{v}.png",
        "plist":"art/poison{v}.plist",
        "start":"poison.1.png",
        "frames":50,
        "delay":0.02,
//        "offset":{
//            "x":0,
//            "y":100
//        },
        "placement":"bottom",
    }
}

