var missileConfig = {
                     "greenbullet":{
                         "png":dirImg + "missiles{v}.png",
                         "plist":dirImg + "missiles{v}.plist",
                         "start":"greenbullet.1.png",
                         "effect":"hit",
                         "frames":27,
                         "delay":0.02 ,
                         "first":9,
                         "speed":300,
						 "height":150
                     },
                     "arrowFire":{
                         "png":dirImg + "missiles{v}.png",
                         "plist":dirImg + "missiles{v}.plist",
                         "start":"arrowFire.1.png",
						 "hasDirection":true,
						 "rotation":"arrow",
                         "initialAngle":-45,
						 "path":"arrow",
                         "speed":350,
						 "height":200,
                         "frames":6,
                         "delay":0.02
                     },
                    "arrowPoison":{
                        "png":dirImg + "missiles{v}.png",
                        "plist":dirImg + "missiles{v}.plist",
                        "start":"arrowPoison.1.png",
                        "hasDirection":true,
                        "rotation":"arrow",
                        "initialAngle":-45,
                        "path":"arrow",
                        "speed":350,
                        "height":200,
                        "frames":6,
                        "delay":0.02
                    },
                    "arrowVoid":{
                        "png":dirImg + "missiles{v}.png",
                        "plist":dirImg + "missiles{v}.plist",
                        "start":"arrowVoid.1.png",
                        "hasDirection":true,
                        "rotation":"arrow",
                        "initialAngle":-45,
                        "path":"arrow",
                        "speed":350,
                        "height":200,
                        "frames":6,
                        "delay":0.02
                    },
                    "arrowNormal":{
                        "png":dirImg + "missiles{v}.png",
                        "plist":dirImg + "missiles.plist",
                        "start":"arrowNormal.1.png",
                        "hasDirection":true,
                        "initialAngle":-45,
                        "path":"arrow",
                        "rotation":"arrow",
                        "speed":350,
                        "frames":2,
                        "delay":0.02

                    },
                    "bomb":{
                        "png":dirImg + "missiles{v}.png",
                        "plist":dirImg + "missiles{v}.plist",
                        "start":"bomb.1.png",
                        "frames":8,
                        "delay":0.1,
                        "path":"jump",
                        "effect":"explo",
                        "speed":170
                    },
                    "magicFire":{
                        "png":dirImg + "missiles{v}.png",
                        "plist":dirImg + "missiles{v}.plist",
                        "start":"magicFire.1.png",
                        "frames":6,
                        "delay":0.03,
                        "path":"bullet",
                        "speed":800,
                        "hasDirection":true,
                        "effect":"hit",
                    },
                    "magicVoid":{
                        "png":dirImg + "missiles{v}.png",
                        "plist":dirImg + "missiles{v}.plist",
                        "start":"magicVoid.1.png",
                        "frames":6,
                        "delay":0.03,
                        "speed":800,
                        "hasDirection":true,
                        "path":"bullet",
                        "effect":"hit",
                    },
                    "magicNormal":{
                        "png":dirImg + "missiles{v}.png",
                        "plist":dirImg + "missiles{v}.plist",
                        "start":"magicNormal.1.png",
                        "frames":6,
                        "delay":0.03,
                        "speed":800,
                        "hasDirection":true,
                        "path":"bullet",
                        "effect":"hit",
                    },
                    "ballFire":{
                        "png":dirImg + "missiles{v}.png",
                        "plist":dirImg + "missiles{v}.plist",
                        "start":"ballFire.1.png",
                        "frames":7,
                        "delay":0.01,
                        "effect":"explo",
                        "speed":600,
                    },
                    "ballVoid":{
                        "png":dirImg + "missiles{v}.png",
                        "plist":dirImg + "missiles{v}.plist",
                        "start":"ballVoid.1.png",
                        "frames":6,
                        "delay":0.01,
                        "speed":600,
                    },
                    "cannonball":{
                        "png":dirImg + "missiles{v}.png",
                        "plist":dirImg + "missiles{v}.plist",
                        "start":"cannonball.1.png",
                        "frames":6,
                        "delay":0.05,
                        "effect":"explo",
                        "speed":800,
                        "path":"jump"
                    },


}

